### ISSUE TITLE
Select: default is not selected

### ISSUE THREAD

**Issue by alik-p** [IBM/carbon-components-angular#1798]
## Detailed description

> Describe in detail the issue you're having.

I use Select component `<ibm-select>` with reactive form. The form contains default value of select. 
After update carbon packages to the latest versions, an appropriate option with this value is not selected anymore.
I have to add an additional `[selected]` logic to every `<option>` in order to workaround this. 

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Yes, to `Select` component.

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect the option with form control value is selected when component is initialized (no need to add the `selected` property to options).  

> What browser are you working in?

Google Chrome Version 89.0.4389.128 

> What version of the Carbon Design System are you using?

```
carbon-components:  10.33.0
carbon-components-angular: 4.48.1
```

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Product of IBM. ASAP.

## Steps to reproduce the issue

[Codesandbox](https://codesandbox.io/s/carbon-components-angular-forked-69t43?file=/src/app/app.component.ts)

**Comment by maksym-plotnikov** [comment]
+1

**Comment by Donisius** [comment]
I believe this should be resolved once #1778 is merged

**Comment by maksym-plotnikov** [comment]
@Donisius I still have issues with Reactive Forms - value is not being set. Please check inside Your Storybook - it doesn't work properly https://angular.carbondesignsystem.com/?path=/story/components-select--with-reactive-forms

**Comment by maksym-plotnikov** [comment]
Currently we have to sit tight at version 4.40.1 since it's the most stable one in our case( Event it has some warnings with disabled attributes passed directly (since Reactive Forms Disabled doesn't work)

**Comment by Donisius** [comment]
@maksym-plotnikov I don't think that storybook is up to date yet, are you still unable to set value properly on v4.51.1?

**Comment by maksym-plotnikov** [comment]
@Donisius  Yes I can't. Tried 4.51.1 and 4.52.0

**Comment by Donisius** [comment]
@maksym-plotnikov Sorry for the delay, I haven't been able to take a look at this until now. It seems like `reactive forms`/`ngModel` works properly on the updated storybook example but not in a prod build. I will look deeper into this.
