### ISSUE TITLE
 In Firefox browser clear search icon is not appearing in ibm-search box.

### ISSUE THREAD

**Issue by ShubhankDubey7** [IBM/carbon-components-angular#533]
## Detailed description
we are using Carbon’s  table  in Angular .But In *FireFox* browser  `clear` search icon is not appearing in  basic `ibm-search` box  , which is working fine in *Chrome*.

Codesandbox
https://7znrvjq51.codesandbox.io/

## Additional information
<img width="1272" alt=" In FireFox" src="https://user-images.githubusercontent.com/49271634/57352570-6921fb80-7183-11e9-974b-f52cc6113fa3.png">
<img width="1235" alt="In Chrome" src="https://user-images.githubusercontent.com/49271634/57352571-6921fb80-7183-11e9-93e3-c745d443dc1b.png">

**Comment by cal-smith** [comment]
This should be fixed by https://github.com/IBM/carbon-components-angular/pull/536 which updates the table header to the (updated) v10 style

**Comment by youda97** [comment]
Still an issue in the standalone [toolbar search](https://angular.carbondesignsystem.com/?path=/story/search--toolbar-search). Waiting on https://github.com/carbon-design-system/carbon/issues/2831

**Comment by zvonimirfras** [comment]
Standalone toolbar search doesn't appear to be a thing in the design system and it works fine where it's supposed to (in table), and it's ancient. Closing.
